# Generated by Django 5.2.6 on 2025-09-24 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Name', models.CharField(max_length=20)),
                ('Roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Address', models.TextField()),
                ('Mobile_no', models.BigIntegerField()),
            ],
        ),
    ]
